src/about/urls.py
from django.urls import path
from .views import AboutPageView


app_name = 'about'

urlpatterns = [
    path('', AboutPageView.as_view(), name='about'),
]

src/blog/urls.py
from django.urls import path, include
from user.admin import admin_site

from django.contrib import admin

urlpatterns = [
    path('thealternativepath/', admin_site.urls),
    path('blog/', include('articles.urls')),
    path('about/', include('about.urls')),
    path('boating/', include('boating.urls')),
    path('', include('core.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

src/core/urls.py
from django.urls import include, path
from blog.settings import base as settings 
from django.conf.urls.static import static

from .views import HomePageView

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/models.py
from django.db import models

from django_ckeditor_5.fields import CKEditor5Field


class ContentSnippet(models.Model):
    title = models.CharField(max_length=100, null=True)
    ident = models.CharField(max_length=50, db_index=True)
    content = CKEditor5Field('content', config_name = 'extends')

    def __str__(self):
        return self.ident

src/core/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from articles.models import Article
from .models import ContentSnippet

class HomePageView(ListView):
    template_name = 'core/home.html'
    context_object_name = 'articles'
    queryset = Article.objects.order_by('created_at')

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Retrieve ContentSnippet entries
        content_snippets = ContentSnippet.objects.filter(ident__in=["introduction", "about"])
        snippets = {snippet.ident: snippet for snippet in content_snippets}
        
        context['content_snippet_intro'] = snippets.get("introduction")
        context['about'] = snippets.get("about")
        
        return context

src/core/templates/core/base.html
{% load static %}
{% load sass_tags %}
{% load compress %}


<html lang='en'>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <link rel="icon" type="image/png" href="{% static 'core/logos/circle.png' %}">
        <title>{% block title %}Alexander Eriksson{% endblock %}</title>
        {% compress css %}
                <link rel='stylesheet' href='{% sass_src 'core/css/style.scss' %}'>
                {% block head %}
                {% endblock %}
        {% endcompress %}
        {% block javascript %}
            <script type="text/javascript" src="{% static 'core/js/jquery.min.js' %}"></script>
            <script src="https://d3js.org/d3.v7.min.js"></script>
            <script type="text/javascript" src="{% static 'core/js/functions.js' %}"></script>
        {% endblock %}
    </head>
    {% include 'core/partials/header.html' %}
    <body>
        {% include 'core/partials/sidebar.html' %}
        {% block content %}
            
        {% endblock %}
    </body>
</html>

src/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% load sass_tags %}


{% block content %}
<main>
    <section class="container flex flex-row flex-responsive sec-def">
        <div class="flex flex-col flex-b-100 flex-jc-center">
            <div class="txt-div">
                <h1 class="container-txt">{{ content_snippet_intro.title | safe }}</h1>
                {{ content_snippet_intro.content | safe }}
            </div>
            <div class="flex flex-jc-center md-my">
                {% include 'core/partials/socialmedia_icons.html' %}
            </div>
            <div class="flex flex-jc-center md-mb">
                <a class="btn-cta-2" href="{% url 'about:about' %}#cv">Läs CV...</a>
            </div>
        </div>
        <div class="flex flex-col flex-b-100 xxl--mx">
            <div class="flex flex-jc-end flex-responsive-jc-c">
                <img class="w-full max-w-40p sm-m of-cover br-10" src="{% static 'core/images/f1.jpg' %}" alt="">
                <img class="w-full max-w-40p sm-m of-cover br-10" src="{% static 'core/images/f2.jpg' %}" alt="">
            </div>
            <div class="flex flex-jc-end flex-responsive-jc-c">
                <img class="w-full max-w-40p sm-m of-cover br-10" src="{% static 'core/images/f3.jpg' %}" alt="">
                <img class="w-full max-w-40p sm-m of-cover br-10" src="{% static 'core/images/fb4.jpg' %}" alt="">
            </div>
        </div>
    </section>
    <section class="container xxl-my sec-def">
        <div class="txt-div">
            {{ about.content | truncatechars:580 | safe}}
        </div>
        <p class="xl-mt">
            <a class="btn-cta-1 xs-p" href="{% url 'about:about' %}#politik">Fortsätt läsa...</a>
        </p>
    </section>
    <section class="container sec-ctr xxl-my sec-def">
        <h1 class="txt-a-center xl-mb">Blogg</h1>
        {% include 'articles/partials/list_view.html' %}
    </section>
</main>
{% endblock %}