src/articles/urls.py
from django.urls import path

from .views import (ArticleDetailView, ArticleListView, AddPostView, 
                    DeletePostView, UpdatePostView, ManageArticlesListView
                    )

app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='index'),
    path('manage/', ManageArticlesListView.as_view(), name='manage'),
    path('manage/add/', AddPostView.as_view(), name='add'),
    path('manage/edit/<slug:slug>', UpdatePostView.as_view(), name='edit'),
    path('manage/delete/<slug:slug>', DeletePostView.as_view(), name='delete'),
    path('<slug:slug>/', ArticleDetailView.as_view(), name='article'),
]

src/blog/urls.py
from django.urls import path, include
from user.admin import admin_site

from django.contrib import admin

urlpatterns = [
    path('thealternativepath/', admin_site.urls),
    path('blog/', include('articles.urls')),
    path('about/', include('about.urls')),
    path('boating/', include('boating.urls')),
    path('', include('core.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

src/articles/models.py
from django.db import models

from django.core.validators import MaxLengthValidator
from django_ckeditor_5.fields import CKEditor5Field
from django.conf import settings
from autoslug import AutoSlugField
from django.urls import reverse


class Article(models.Model):

    CATEGORY_CHOICES = [
        ('boating', 'Boating'),
        ('motorcycling', 'Motorcycling'),
        ('software_development', 'Software Development'),
        ('investing', 'Investing'),
        ('other', 'Other'),
        ('politics', 'Politics')
    ]

    LANGUAGE = [
            ('se', 'Swedish'),
            ('en', 'English')
            ]

    title = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to='articles/thumbnails')
    entry = CKEditor5Field('Entry', config_name = 'default', validators=[MaxLengthValidator(500)], null=True, blank=True)
    content = CKEditor5Field('Body', config_name='extends', null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    language = models.CharField(max_length=20, choices=LANGUAGE, default='se')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published = models.BooleanField() 
    slug = AutoSlugField(populate_from='title', unique=True, default=None)  
    references = CKEditor5Field('References', config_name='extends', null=True, blank=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, null=True)
    
    def get_absolute_url(self):
        return reverse('articles:article', kwargs={'slug': self.slug})  

    def get_category_display_name(self):
        return dict(self.CATEGORY_CHOICES).get(self.category, 'Unknown')

    def get_language_display_name(self):
        return dict(self.LANGUAGE).get(self.language, 'Unknown')

    def __str__(self):
        return str(self.title)

src/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article

        fields = ['title', 
                  'author', 
                  'language',
                  'category', 
                  'thumbnail', 
                  'published',  
                  'entry', 
                  'content',
                  'references', 
                  ]

src/articles/views.py
from django.shortcuts import render

from user.mixins import GroupMixin
from .models import Article
from django.views.generic.detail import DetailView
from django.views.generic import DeleteView, ListView, CreateView, UpdateView
from hitcount.views import HitCountDetailView
from django.urls import reverse, reverse_lazy
from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404

from .forms import ArticleForm

from user.mixins import StaffRequiredMixin


app_name = 'articles'


class ArticleListView(GroupMixin, ListView):
    model = Article
    template_name = 'articles/article-list.html'  
    context_object_name = 'articles'  
    ordering = ['created_at']
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_is_editor'] = self.user_in_group('Editor')
        return context


    def get_queryset(self):
        return Article.objects.order_by('created_at')

class ArticleDetailView(GroupMixin, HitCountDetailView):
    model = Article
    template_name = 'articles/article.html'
    context_object_name = 'article'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        context['article'] = article
        context['user_is_editor'] = self.user_in_group('Editor')
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        article = self.object

        # Check if the article is not published and the user is not an editor
        if not article.published and not self.user_in_group('Editor'):
            raise Http404("Article not found")

        return super().get(request, *args, **kwargs)



class ManageArticlesListView(ArticleListView):
    template_name = 'articles/manage/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_is_editor'] = self.user_in_group('Editor')
        return context


class AddPostView(StaffRequiredMixin, CreateView):
    model = Article
    template_name = 'articles/manage/add_post.html'
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('articles:article', args=[self.object.slug])


class UpdatePostView(StaffRequiredMixin, UpdateView):
    model = Article
    template_name = 'articles/manage/update_post.html'
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('articles:article', args=[self.object.slug])


class DeletePostView(StaffRequiredMixin, DeleteView):

    model = Article
    template_name = 'articles/manage/delete_post.html'
    success_url = reverse_lazy('articles:index')

src/articles/templates/articles/add_post.html
{% extends 'core/base.html' %}
{% load static %}
{% load sass_tags %}

{% block title %}{% endblock %}



{% block content %}
<main>
    <section class="container">
        <h1>Add Post</h1>
        <form method="POST" enctype="multipart/form-data" class="form-default">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <button class="btn-cta-1 xs-p"">Publish</button>
        </form>
    </section>
</main>
{% endblock %}

src/articles/templates/articles/article-list.html
{% extends 'core/base.html' %}
{% load static %}
{% load sass_tags %}

{% block title %}Blogg | Alexander Eriksson{% endblock %}

{% block content %}
<main class="container">
    {% if user_is_editor %}
        <div class="xl-my">
            <a href="{% url 'articles:manage' %}" class="btn-cta-1 xs-p">Manage Posts</a>
        </div>
    {% endif %}
    {% include 'articles/partials/grid_view.html' %}
</main>
<div class="pagination txt-a-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn" href="?page={{ page_obj.previous_page_number }}">&laquo</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <span class="btn btn--current">{{ num }}</span>
            {% else %}
                <a class="btn btn--not-current" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn" href="?page={{ page_obj.next_page_number }}">&raquo</a>
        {% endif %}
    </span>
</div>
{% endblock %}

src/articles/templates/articles/article.html
{% extends 'core/base.html' %}
{% load static %}
{% load sass_tags %}
{% load hitcount_tags %}


{% block title %}
  {{ article.title }}
{% endblock %}

{% block content %}
<main class="container">
    <article class="post">
        <img class="post-img" src="{{ article.thumbnail.url }}" alt="">
        {% if user_is_editor %}
            <p>
               <a class="btn-cta-1 xs-p" href="{% url 'articles:edit' slug=article.slug %}">Edit Post</a>
               <a class="btn-cta-warning xs-p" href="{% url 'articles:delete' slug=article.slug %}">Delete Post</a>
            </p>
        {% endif %}
        <h1 class="post-title">{{ article.title }}</h1>
        <time class="post-time">{{ article.created_at | date:"d M Y" }}</time>
        <div class="post-entry bold">{{ article.entry | safe }}</div>
        <div class="post-body">
            {{ article.content | safe }}
        </div>

        {% if article.references %}
            <div class="post-references">
                <h1>Referenser</h1>
                {{ article.references | safe }}
            </div>
        {% endif %}
    </article>
</main>
{%  endblock %}